version: '3.1'

services:

  mongo:
    image: mongo
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=ohd-files

  mmt:
    depends_on:
      - mongo
    image: mmt
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - MMT_MONGODB_CONNECTION_STRING=mongodb://mongo:27017/ohd-files
      - MMT_USER_FILES_DIR=/app/user_files
